# Generated by Django 2.1.3 on 2018-12-09 21:50

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradelistingpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='tradelistingpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock())], default=''),
            preserve_default=False,
        ),
    ]
