# Generated by Django 2.1.3 on 2019-05-04 10:55

from django.db import migrations
import dmcTrade.trade.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20181222_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelistingpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('section_block', wagtail.core.blocks.ListBlock(dmcTrade.trade.models.ItemBlock))]),
        ),
    ]
