# Generated by Django 2.1.3 on 2019-05-08 21:05

from django.db import migrations, models
import dmcTrade.trade.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_auto_20190508_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelistingpage',
            name='card_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradelistingpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(blank=True)), ('section_block', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.RichTextBlock(blank=True)), ('items', wagtail.core.blocks.ListBlock(dmcTrade.trade.models.ItemBlock))]))]),
        ),
    ]
