# Generated by Django 2.1.3 on 2019-05-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_auto_20190508_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradelistingpage',
            name='card_price',
        ),
    ]
